services:
  codepix-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mayank13828/codepix-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
