services:
  codepix-backend-nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
    image: codepix-backend-nextjs:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: unless-stopped
    environment:
      - NODE_ENV=production
